# Generated by Django 6.0 on 2025-12-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
    ]
