# Generated by Django 6.0 on 2025-12-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20251224_2355'),
    ]

    operations = [
    ]
